# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPassengers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPassengers(object):
    def setupUi(self, AddPassengers):
        AddPassengers.setObjectName("AddPassengers")
        AddPassengers.resize(1381, 768)
        self.label = QtWidgets.QLabel(AddPassengers)
        self.label.setGeometry(QtCore.QRect(580, 30, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddPassengers)
        self.label_2.setGeometry(QtCore.QRect(370, 110, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddPassengers)
        self.label_3.setGeometry(QtCore.QRect(370, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddPassengers)
        self.label_4.setGeometry(QtCore.QRect(370, 400, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AddPassengers)
        self.label_5.setGeometry(QtCore.QRect(800, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(AddPassengers)
        self.lineEdit.setGeometry(QtCore.QRect(370, 170, 231, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(AddPassengers)
        self.pushButton.setGeometry(QtCore.QRect(150, 590, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(AddPassengers)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 310, 231, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(AddPassengers)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 440, 231, 61))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(AddPassengers)
        self.lineEdit_4.setGeometry(QtCore.QRect(800, 170, 281, 61))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(AddPassengers)
        self.comboBox.setGeometry(QtCore.QRect(800, 310, 281, 61))
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(AddPassengers)
        self.label_6.setGeometry(QtCore.QRect(800, 270, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(AddPassengers)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 590, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AddPassengers)
        QtCore.QMetaObject.connectSlotsByName(AddPassengers)

    def retranslateUi(self, AddPassengers):
        _translate = QtCore.QCoreApplication.translate
        AddPassengers.setWindowTitle(_translate("AddPassengers", "Регистрация пассажира"))
        self.label.setText(_translate("AddPassengers", "Регистрация пассажира"))
        self.label_2.setText(_translate("AddPassengers", "Номер пассажира"))
        self.label_3.setText(_translate("AddPassengers", "Фамилия"))
        self.label_4.setText(_translate("AddPassengers", "Имя"))
        self.label_5.setText(_translate("AddPassengers", "Паспорт"))
        self.pushButton.setText(_translate("AddPassengers", "Зарегистрировать"))
        self.label_6.setText(_translate("AddPassengers", "Выберите маршрут"))
        self.pushButton_2.setText(_translate("AddPassengers", "На главную"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPassengers = QtWidgets.QWidget()
    ui = Ui_AddPassengers()
    ui.setupUi(AddPassengers)
    AddPassengers.show()
    sys.exit(app.exec_())
