# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Routes222.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRoutes(object):
    def setupUi(self, AddRoutes):
        AddRoutes.setObjectName("AddRoutes")
        AddRoutes.resize(1000, 576)
        self.pushButton_3 = QtWidgets.QPushButton(AddRoutes)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(AddRoutes)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(AddRoutes)
        self.pushButton_6.setGeometry(QtCore.QRect(650, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(AddRoutes)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(AddRoutes)
        self.pushButton.setGeometry(QtCore.QRect(70, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(AddRoutes)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(AddRoutes)
        self.label.setGeometry(QtCore.QRect(370, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(AddRoutes)
        QtCore.QMetaObject.connectSlotsByName(AddRoutes)

    def retranslateUi(self, AddRoutes):
        _translate = QtCore.QCoreApplication.translate
        AddRoutes.setWindowTitle(_translate("AddRoutes", "Маршруты"))
        self.pushButton_3.setText(_translate("AddRoutes", "Обновить таблицу"))
        self.pushButton_2.setText(_translate("AddRoutes", "Редактировать"))
        self.pushButton_6.setText(_translate("AddRoutes", "Поиск маршрута"))
        self.pushButton_4.setText(_translate("AddRoutes", "Удалить запись"))
        self.pushButton.setText(_translate("AddRoutes", "Добавить маршрут"))
        self.pushButton_5.setText(_translate("AddRoutes", "На главную "))
        self.label.setText(_translate("AddRoutes", "Маршруты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddRoutes = QtWidgets.QWidget()
    ui = Ui_AddRoutes()
    ui.setupUi(AddRoutes)
    AddRoutes.show()
    sys.exit(app.exec_())
