# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditPass(object):
    def setupUi(self, EditPass):
        EditPass.setObjectName("EditPass")
        EditPass.resize(489, 452)
        self.label = QtWidgets.QLabel(EditPass)
        self.label.setGeometry(QtCore.QRect(100, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(EditPass)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(EditPass)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(EditPass)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(EditPass)
        self.label_5.setGeometry(QtCore.QRect(270, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(EditPass)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(EditPass)
        self.pushButton.setGeometry(QtCore.QRect(290, 380, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(EditPass)
        self.lineEdit.setGeometry(QtCore.QRect(30, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(EditPass)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(EditPass)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(EditPass)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(EditPass)
        self.comboBox.setGeometry(QtCore.QRect(30, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(EditPass)
        QtCore.QMetaObject.connectSlotsByName(EditPass)

    def retranslateUi(self, EditPass):
        _translate = QtCore.QCoreApplication.translate
        EditPass.setWindowTitle(_translate("EditPass", "Редактирование пассажира"))
        self.label.setText(_translate("EditPass", "Редактирование пассажира"))
        self.label_2.setText(_translate("EditPass", "Паспорт"))
        self.label_3.setText(_translate("EditPass", "Фамилия"))
        self.label_4.setText(_translate("EditPass", "Номер поездки"))
        self.label_5.setText(_translate("EditPass", "Имя"))
        self.label_6.setText(_translate("EditPass", "Выберите маршрут"))
        self.pushButton.setText(_translate("EditPass", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditPass = QtWidgets.QWidget()
    ui = Ui_EditPass()
    ui.setupUi(EditPass)
    EditPass.show()
    sys.exit(app.exec_())
