# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Passengers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Passengers(object):
    def setupUi(self, Passengers):
        Passengers.setObjectName("Passengers")
        Passengers.resize(872, 576)
        self.pushButton_3 = QtWidgets.QPushButton(Passengers)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Passengers)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableView = QtWidgets.QTableView(Passengers)
        self.tableView.setGeometry(QtCore.QRect(20, 50, 831, 261))
        self.tableView.setObjectName("tableView")
        self.pushButton_6 = QtWidgets.QPushButton(Passengers)
        self.pushButton_6.setGeometry(QtCore.QRect(650, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(Passengers)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(Passengers)
        self.pushButton.setGeometry(QtCore.QRect(70, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(Passengers)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(Passengers)
        self.label.setGeometry(QtCore.QRect(310, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(Passengers)
        self.pushButton_7.setGeometry(QtCore.QRect(650, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Passengers)
        QtCore.QMetaObject.connectSlotsByName(Passengers)

    def retranslateUi(self, Passengers):
        _translate = QtCore.QCoreApplication.translate
        Passengers.setWindowTitle(_translate("Passengers", "Пассажиры"))
        self.pushButton_3.setText(_translate("Passengers", "Поиск"))
        self.pushButton_2.setText(_translate("Passengers", "Удалить запись"))
        self.pushButton_6.setText(_translate("Passengers", "Обновить "))
        self.pushButton_4.setText(_translate("Passengers", "Посмотреть поезки"))
        self.pushButton.setText(_translate("Passengers", "Изменить запись"))
        self.pushButton_5.setText(_translate("Passengers", "На главную "))
        self.label.setText(_translate("Passengers", "Пассажиры"))
        self.pushButton_7.setText(_translate("Passengers", "Печать билета"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Passengers = QtWidgets.QWidget()
    ui = Ui_Passengers()
    ui.setupUi(Passengers)
    Passengers.show()
    sys.exit(app.exec_())
