# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Statikpokaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statikpokaz(object):
    def setupUi(self, Statikpokaz):
        Statikpokaz.setObjectName("Statikpokaz")
        Statikpokaz.resize(485, 336)
        font = QtGui.QFont()
        font.setPointSize(12)
        Statikpokaz.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(Statikpokaz)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 441, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Statikpokaz)
        QtCore.QMetaObject.connectSlotsByName(Statikpokaz)

    def retranslateUi(self, Statikpokaz):
        _translate = QtCore.QCoreApplication.translate
        Statikpokaz.setWindowTitle(_translate("Statikpokaz", "Результат"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Statikpokaz", "Фамлия"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Statikpokaz", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Statikpokaz", "Дата отправления"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Statikpokaz = QtWidgets.QWidget()
    ui = Ui_Statikpokaz()
    ui.setupUi(Statikpokaz)
    Statikpokaz.show()
    sys.exit(app.exec_())
