# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Statik.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statik(object):
    def setupUi(self, Statik):
        Statik.setObjectName("Statik")
        Statik.resize(1366, 781)
        self.label = QtWidgets.QLabel(Statik)
        self.label.setGeometry(QtCore.QRect(370, 60, 671, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Statik)
        self.label_2.setGeometry(QtCore.QRect(380, 280, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Statik)
        self.label_3.setGeometry(QtCore.QRect(780, 280, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Statik)
        self.pushButton.setGeometry(QtCore.QRect(380, 580, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Statik)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 580, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Statik)
        self.comboBox.setGeometry(QtCore.QRect(380, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Statik)
        self.comboBox_2.setGeometry(QtCore.QRect(780, 330, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")

        self.retranslateUi(Statik)
        QtCore.QMetaObject.connectSlotsByName(Statik)

    def retranslateUi(self, Statik):
        _translate = QtCore.QCoreApplication.translate
        Statik.setWindowTitle(_translate("Statik", "Statik"))
        self.label.setText(_translate("Statik", "Статистика по количеству пассажиров "))
        self.label_2.setText(_translate("Statik", "Выберите время"))
        self.label_3.setText(_translate("Statik", "Выберите маршрут"))
        self.pushButton.setText(_translate("Statik", "Показать"))
        self.pushButton_2.setText(_translate("Statik", "На главную"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Statik()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
